package token

import (
	"testing"
	"time"
)

func TestSignVerifyRoundTrip(t *testing.T) {
	s := New("secret-a")
	tok, err := s.Sign(Claims{Kind: KindEvent, EventID: "e1",
		ExpiresAt: time.Now().Add(time.Hour).Unix()})
	if err != nil {
		t.Fatal(err)
	}
	c, err := s.Verify(tok, KindEvent)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if c.EventID != "e1" {
		t.Fatalf("event id = %q", c.EventID)
	}
}

func TestExpired(t *testing.T) {
	s := New("k")
	tok, _ := s.Sign(Claims{Kind: KindSession, ExpiresAt: time.Now().Add(-time.Second).Unix()})
	if _, err := s.Verify(tok, KindSession); err != ErrExpired {
		t.Fatalf("want ErrExpired, got %v", err)
	}
}

func TestKindMismatch(t *testing.T) {
	s := New("k")
	tok, _ := s.Sign(Claims{Kind: KindAuth, ExpiresAt: time.Now().Add(time.Hour).Unix()})
	if _, err := s.Verify(tok, KindEvent); err != ErrKind {
		t.Fatalf("want ErrKind, got %v", err)
	}
}

func TestRoleParticipantRoundTrip(t *testing.T) {
	s := New("secret-b")
	tok, err := s.Sign(Claims{Kind: KindAuth, Role: RoleParticipant, Subject: "p42",
		ExpiresAt: time.Now().Add(time.Hour).Unix()})
	if err != nil {
		t.Fatal(err)
	}
	c, err := s.Verify(tok, KindAuth)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if c.Role != RoleParticipant {
		t.Fatalf("role = %q, want %q", c.Role, RoleParticipant)
	}
	if c.Subject != "p42" {
		t.Fatalf("subject = %q", c.Subject)
	}
}

func TestJTIAutoGenerated(t *testing.T) {
	s := New("secret-c")
	exp := time.Now().Add(time.Hour).Unix()
	tok1, err := s.Sign(Claims{Kind: KindAuth, ExpiresAt: exp})
	if err != nil {
		t.Fatal(err)
	}
	tok2, err := s.Sign(Claims{Kind: KindAuth, ExpiresAt: exp})
	if err != nil {
		t.Fatal(err)
	}
	c1, err := s.Verify(tok1, KindAuth)
	if err != nil {
		t.Fatalf("verify tok1: %v", err)
	}
	c2, err := s.Verify(tok2, KindAuth)
	if err != nil {
		t.Fatalf("verify tok2: %v", err)
	}
	if c1.JTI == "" {
		t.Fatal("JTI should be non-empty")
	}
	if c1.JTI == c2.JTI {
		t.Fatalf("two Sign calls produced same JTI: %q", c1.JTI)
	}
}

func TestJTIExplicitPreserved(t *testing.T) {
	s := New("secret-d")
	const jti = "my-explicit-jti"
	tok, err := s.Sign(Claims{Kind: KindAuth, JTI: jti, ExpiresAt: time.Now().Add(time.Hour).Unix()})
	if err != nil {
		t.Fatal(err)
	}
	c, err := s.Verify(tok, KindAuth)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if c.JTI != jti {
		t.Fatalf("JTI = %q, want %q", c.JTI, jti)
	}
}

func TestPermRoundTrip(t *testing.T) {
	s := New("secret-e")
	perm := map[string]bool{"can_create_event": true, "can_export_records": false}
	tok, err := s.Sign(Claims{
		Kind:        KindAuth,
		Role:        RoleOrganizer,
		Perm:        perm,
		PermVersion: 7,
		ExpiresAt:   time.Now().Add(time.Hour).Unix(),
	})
	if err != nil {
		t.Fatal(err)
	}
	c, err := s.Verify(tok, KindAuth)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if c.PermVersion != 7 {
		t.Fatalf("PermVersion = %d, want 7", c.PermVersion)
	}
	if len(c.Perm) != 2 {
		t.Fatalf("Perm len = %d, want 2", len(c.Perm))
	}
	if !c.Perm["can_create_event"] {
		t.Fatal("can_create_event should be true")
	}
	if c.Perm["can_export_records"] {
		t.Fatal("can_export_records should be false")
	}
}

func TestTamperAndWrongSecret(t *testing.T) {
	s := New("right")
	tok, _ := s.Sign(Claims{Kind: KindEvent, ExpiresAt: time.Now().Add(time.Hour).Unix()})
	if _, err := New("wrong").Verify(tok, KindEvent); err != ErrSignature {
		t.Fatalf("want ErrSignature for wrong secret, got %v", err)
	}
	if _, err := s.Verify(tok+"x", KindEvent); err == nil {
		t.Fatal("tampered token verified")
	}
}
